/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladorprocesos;

import java.awt.Dimension;
import javax.swing.JLabel;


/**
 *
 * @author pablo
 */
public class CicleProcessGUI extends Arrow_Test {

    /**
     * Creates new form CicleProcessGUI
     */
    public CicleProcessGUI() {
        initComponents();
        setSize(new Dimension(756, 344));
        initArrows(label0, label1, 1);
        initArrows(label1, label2, 0);
        initArrows(label2, label3, 0);
        initArrows(label0, label3, true, 2);
        repaint();
    }

    void initArrows(JLabel a, JLabel b, int type) {
        super.addArrow(a.getWidth() + a.getX(), (a.getHeight() + a.getY()) / 2, b.getX(), (b.getHeight() + b.getY()) / 2, type);
    }
    
    void initArrows(JLabel a, JLabel b, boolean f, int type) {
        super.addArrow(a.getWidth() + a.getX(), (a.getHeight() - a.getY()), b.getX(), (b.getHeight() - b.getY()), type);
    }
    
    void backUpdateArrows(int i, JLabel a, JLabel b, int y) {
        super.updateArrows(i, a.getWidth() + a.getX() , (a.getHeight() + a.getY() + y) / 2, b.getX(), (b.getHeight() + b.getY() + y) / 2);
    }
    
    void backUpdateArrows(int i, JLabel a, JLabel b, int y, boolean f) {
        super.updateArrows(i, a.getWidth() + a.getX(), (a.getHeight() + a.getY() + y), b.getX(), (b.getHeight() + b.getY() + y));
    }
    
    public void updateAllArrows(int x){
        backUpdateArrows(0, label0, label1, x);
        backUpdateArrows(1, label1, label2, x);
        backUpdateArrows(2, label2, label3, x);
        backUpdateArrows(3, label0, label3, x, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        label3 = new javax.swing.JLabel();
        label0 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(61, 63, 65));
        setPreferredSize(new java.awt.Dimension(759, 430));
        setLayout(null);

        label3.setBackground(new java.awt.Color(204, 0, 0));
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label3.setOpaque(true);
        add(label3);
        label3.setBounds(600, 20, 136, 370);

        label0.setBackground(new java.awt.Color(0, 0, 153));
        label0.setForeground(new java.awt.Color(255, 255, 255));
        label0.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label0.setOpaque(true);
        add(label0);
        label0.setBounds(10, 20, 136, 370);

        label1.setBackground(new java.awt.Color(0, 255, 0));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label1.setOpaque(true);
        add(label1);
        label1.setBounds(200, 50, 136, 230);

        label2.setBackground(new java.awt.Color(255, 255, 51));
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        label2.setOpaque(true);
        add(label2);
        label2.setBounds(390, 20, 136, 260);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bloqueado");
        add(jLabel1);
        jLabel1.setBounds(630, 0, 70, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Listo");
        add(jLabel2);
        jLabel2.setBounds(60, 0, 28, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ejecutando");
        add(jLabel3);
        jLabel3.setBounds(230, 30, 70, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Terminado");
        add(jLabel4);
        jLabel4.setBounds(420, 0, 70, 16);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel label0;
    public javax.swing.JLabel label1;
    public javax.swing.JLabel label2;
    public javax.swing.JLabel label3;
    // End of variables declaration//GEN-END:variables
}
